---
title: Angelotieres.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Tieresaurus
author: Angelo Tiéres
description: Um dinossauro da época dos disquetes...
avatar: "/images/tieresaurus_pixel.png"
footer-links:
  dribbble: 
  email: 
  facebook: 
  flickr: 
  github: github.com/angelotieres
  instagram: 
  linkedin: linkedin.com/in/angelotieres/
  pinterest: 
  rss: rss
  twitter: 
  stackoverflow: 
  youtube: 
  googleplus: 
  playconsole: 
  mastodon: 
disqus: 
google_analytics: 
url: http://www.tieresaurus.com
enforce_ssl: https://www.tieresaurus.com
baseurl: ''
permalink: "/:title/"
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
sass:
  style: :expanded
plugins:
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-paginate
include:
- _pages
paginate: 3
paginate_path: "/page:num/"
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
